version: '3.8'
services:

  attacker:
    container_name: attacker
    build:
      context: .
      dockerfile: ./attacker/Dockerfile.attacker
    extra_hosts:
      - "www.rebel-alliance.com:192.168.100.1"
    networks:
      external_network:
        ipv4_address: 192.168.100.2

  honeypot:
    container_name: honeypot
    image: cowrie/cowrie:latest
    ports:
        - "2222:2222"
        - "2223:2223"
    env_file:
      - .env
    networks:
      external_network:
        ipv4_address: 192.168.100.3

  reverse_proxy:
    container_name: nginx
    build:
      context: .
      dockerfile: ./reverse_proxy/Dockerfile.proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_config:/etc/nginx/conf.d
      - ./nginx_logs:/var/log/nginx
    restart: always
    depends_on:
      - web_server
    networks:
      dmz_network:
        ipv4_address: 192.168.101.2

  web_server:
    container_name: web
    build:
      context: .
      dockerfile: ./web_server/Dockerfile.apache
    networks:
      dmz_network:
        ipv4_address: 192.168.101.3

  autogen:
    container_name: autogen
    build:
      context: .
      dockerfile: ./autogen/Dockerfile.autogen
    env_file:
      - .env
    volumes:
      - ./autogen/var:/var
      - ./honeypot:/var/log/cowrie
      - nginx_config:/etc/nginx/conf.d
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      agent_network:
        ipv4_address: 192.168.102.2
    depends_on:
      - honeypot

networks:
  external_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
  dmz_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.101.0/24
  agent_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.102.0/24

volumes:
  nginx_config:
